language: go
go:
    - 1.2

script:
    - go get code.google.com/p/go.tools/cmd/goimports
    - go get launchpad.net/gocheck
    - go get code.google.com/p/gomock/gomock
    - go get github.com/qur/withmock
    - go get github.com/qur/withmock/mocktest
    - export GOPATH=/home/travis/gopath
    - export PATH=$PATH:/home/travis/gopath/bin

    - cd $TRAVIS_BUILD_DIR/container && withmock go test . -v -debug
    - cd $TRAVIS_BUILD_DIR/gaudi && withmock go test . -v -debug
