language: go
go:
    - 1.2

script:
    - go get code.google.com/p/go.tools/cmd/goimports
    - go get launchpad.net/gocheck
    - go get github.com/qur/withmock
    - go get github.com/qur/withmock/mocktest
    
    - cd build/marmelab/arch-o-match && withmock go test -v
